### ISSUE TITLE
Testing and Documentation

### ISSUE THREAD

**Issue by sharonmleon** [omeka-s-modules/OhmsEmbed#1] opened 2024-10-21 15:24 UTC
This module is designed to create a special viewer for content developed in the Oral History Metadata Synchronizer application. It contains an Omeka S specific viewer and a method for importing an XML file that can include metadata, transcript, translation, and time code indexing.

There is an initial draft of the documentation that can be reviewed and updated. The screenshots leave something to be desired.

https://github.com/omeka/omeka-s-enduser/blob/OhmsEmbed/docs/modules/ohmsembed.md

And here are a set of sample OHMS XML files.
[ohms_xml_samples.zip](https://github.com/user-attachments/files/17463195/ohms_xml_samples.zip)

This module must be released by October 28, 2024.

**Comment by allanaaa** [comment] 2024-10-21 16:53
On first glance this seems to work fine. I am getting a "blocked" error from the first of the XML files you included:

<img width="1310" alt="Screenshot 2024-10-21 at 11 40 16" src="https://github.com/user-attachments/assets/688e5c6e-69b0-47ac-bbd2-b7d95f70ec0f">

The second one, with a Youtube video, works just fine. 

For the most part this seems straightforward. 


1) In case of editing the OHMS files: 

The "OHMS Editor" is the online application that you need a free account for? 

I'm imagining a workflow where somebody is creating and exporting all these XML files, and then some Omeka administrator is just doing the uploading. Is there a workaround for that person? Can I just edit these XML files by putting in the new Omeka media URL? 

2) In case of using Extract Metadata:

I'm not getting anything. OHMS is showing as an extractor and it's enabled. But my XML files are showing as having the ExifTool extractor running on them:

<img width="743" alt="Screenshot 2024-10-21 at 12 50 22" src="https://github.com/user-attachments/assets/1850522b-2293-4f49-9e29-c7b11d140ab9">

When I disable this and run it with only the OHMS extractor working, nothing happens. 
I assume something should show on this tab whether I have the mapping set up or not?

**Comment by allanaaa** [comment] 2024-10-21 16:57
On the front-end, the audio player isn't rendering quite right with our Media embed block @kimisgold - when it's set to "Vertical" - but it looks okay otherwise:

http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/page/ohms-test

<img width="535" alt="Screenshot 2024-10-21 at 12 57 36" src="https://github.com/user-attachments/assets/44d7b2c4-4c34-477a-8106-f1ff5b18a9fd">

**Comment by allanaaa** [comment] 2024-10-21 17:23
Another Q: Will any of these media be text-searchable if we don't use Extract Text?

**Comment by kimisgold** [comment] 2024-10-21 17:52
I just pushed [a fix for the audio](https://github.com/omeka/ohms.js/commit/f7841040f64e3a03cf47431c631c41367c58634b). It should have been pulled into the module in https://github.com/omeka-s-modules/OhmsEmbed/commit/b82a70039350e6531df14447896df57467b1f230.

**Comment by zerocrates** [comment] 2024-10-21 18:47
hmm the Extract Metadata thing is odd. exiftool will run on basically everything if enabled but the ohms one should be just working... let me see if I can reproduce the issue

**Comment by zerocrates** [comment] 2024-10-21 19:05
Extract issue should be fixed

**Comment by sharonmleon** [comment] 2024-10-21 19:12
So, there is no way to edit the XML file. That needs to happen in the OHMS application, which is hosted at Aviary and does require a free account.

On the note about the slowness with CSVImport and Extract Metadata running at the same time, have you actually had that issue? Or is this just anticipation?

**Comment by zerocrates** [comment] 2024-10-21 19:13
Error on the video for the first one i think is just down to the file of samples Sharon gave being an old set, so that one points to a no-longer-working video, nothing to be done there. (Them being old is also the source of the extract problem, but that's something we can and should support, so we fixed that).

**Comment by sharonmleon** [comment] 2024-10-21 19:13
On the text searchable issue, we'd have to extract and map the transcript/translation, which would take an enormous amount of resources.

**Comment by allanaaa** [comment] 2024-10-21 21:26
> On the note about the slowness with CSVImport and Extract Metadata running at the same time, have you actually had that issue? Or is this just anticipation?

Just a prediction! We usually warn about this stuff. If I can get Extract Text and Extract Metadata both up and running I'll test it a few times.

**Comment by allanaaa** [comment] 2024-10-22 00:56
> On the text searchable issue, we'd have to extract and map the transcript/translation, which would take an enormous amount of resources.

We *can* use Extract Text, and then hide the output - which I am trying to figure out how best to do. 
You can 
1) set the individual value on each item to "private" (which hides it from logged-out users) 
2) and/or the property itself on a resource template (ditto, only logged-out users) 
3) or you can use the Hide Properties module (hidden for everyone, including on admin if desired). 

All of these mean that the field itself still comes up in search results, as far as I can tell. But let me know if I have any of this wrong.

**Comment by sharonmleon** [comment] 2024-10-22 12:17
We can certainly present those as options. I used the private property mode myself with one of my tests just because I had Extract Text install.

**Comment by sharonmleon** [comment] 2024-10-22 12:18
On the slowness issue, I just haven't noticed it. Perhaps we should make that a note for people on shared hosting?

**Comment by allanaaa** [comment] 2024-10-22 14:13
> Extract issue should be fixed

Looks good. Now if you have Exif and OHMS both enabled, you'll get a result for both. Is that okay? I guess it doesn't make a difference as long as you don't have conflicting Exif mappers set up, right?

<img width="732" alt="Screenshot 2024-10-22 at 10 01 10" src="https://github.com/user-attachments/assets/27480e25-8b5a-4f25-bb7c-be8d9f21a5b3">

On testing, only about half of my crosswalks are working. Things that appear clearly in the EM tab aren't getting mapped to the metadata fields. Do we have all these pointers correct? Some with slashes, some without?

    Record ID: /id
    Record date: /dt
    OHMS Application version: /version
    Interview Date: /date
    Date (Non-preferred format): date_nonpreferred_format
    CMS: /cms_record_id
    Title: /title
    Accession Number: /accession
    Duration: /duration
    Collection ID: /collection_id
    Collection Name: /collection_name
    Series ID: /series_id
    Series (Name): /series_name
    Organization: /repository
    Acknowledgement: /funding
    Organization URL: /repository_url
    Media file: /file_name
    Media ID: /media_id
    Media URL: /media_url
    Language for Translation: /transcript_alt_lang
    Language: /language
    User Notes: /user_notes
    Type: /type
    Summary: /description
    /rel
    Rights Statement: /rights
    Media Format: /fmt
    Usage Statment /usage
    OHMS XML Location: /xmllocation
    OHMS XML Filename: /xmlfilename
    Collection Link: /collection_link
    Series Link: /series_link
    Subject: /subject
    Keywords: keyword
    Interviewee: interviewee
    Interviewer: interviewer
    Format: format.

**Comment by sharonmleon** [comment] 2024-10-22 14:15
Nope that's a screw up on my part. All should have slashes. I'll update.

**Comment by allanaaa** [comment] 2024-10-22 14:26
Do you have a description for "/rel" as well?

**Comment by allanaaa** [comment] 2024-10-22 14:39
I'm specifically not having any luck with subject, keyword, format, interviewer, interviewee (of the ones I've set up so far). 

<img width="1150" alt="Screenshot 2024-10-22 at 10 34 26" src="https://github.com/user-attachments/assets/046acc3b-3318-4c3e-a1bb-3d750ce6e41b">
<img width="794" alt="Screenshot 2024-10-22 at 10 35 03" src="https://github.com/user-attachments/assets/fc734306-c64c-4300-98ac-3708cd6a931a">

**Comment by sharonmleon** [comment] 2024-10-22 14:48
That's interesting and possibly a question for @zerocrates. Those are the variables that can include more than one input, so maybe there is something different about the logic there. I did not have issues with that in my testing.

**Comment by zerocrates** [comment] 2024-10-22 15:07
The multiple ones need an update to Extract Metadata, that's already done, it's just not released. Pulling Extract Metadata should fix the issue

**Comment by allanaaa** [comment] 2024-10-22 15:30
Okay, I uninstalled and reinstalled the module afresh and those fields are working now. I'm not going to test every field in the list but I'll assume this is all good.

I want to run a CSV Import using the 5 files I have and everything set up and turned on; that should be the last test. And, I guess, look at it in each theme. 
I think the documentation is all ready.

**Comment by zerocrates** [comment] 2024-10-22 21:38
A note on search, if I'm remembering the particulars correctly:

- Setting private on the template won't work (extract text doesn't look at the template)
- Setting private on the value will work but only for the advanced search (search by value/property), the text won't come up in the fulltext search
- Using Hide Properties should work fine.

Other notes from looking at the manual changes:

- The OHMS extractor is only present in Extract Metadata if the OHMS Embed module is also installed (OHMS Embed provides that extractor)
- I think we probably don't really need the note to tell people to turn off both extractors when importing, unless we've seen an issue there in practice (I know this got discussed a little before)

**Comment by allanaaa** [comment] 2024-10-23 16:59
I'm only getting one odd CSV Import behaviour, which is that the items are coming up as "Untitled" when Extract Metadata is working fine filling out the title field. 

<img width="669" alt="Screenshot 2024-10-23 at 12 55 04" src="https://github.com/user-attachments/assets/6c0860e9-3cef-4dcb-af22-da28ba46786a">

This may be a CSV Import / EM interaction, not specific to OHMS? They're being imported to a template where the title field is indicated correctly, so that's not the problem.

**Comment by allanaaa** [comment] 2024-10-23 17:27
Themes!

Papers is rendering the narrow version on the item page, and the wide version on the media page:

<img width="1422" alt="Screenshot 2024-10-23 at 13 18 50" src="https://github.com/user-attachments/assets/55bbce71-6051-4390-b7e7-a0290fd6f866">

In the page block wide version, I think there are supposed to be two columns no matter what content - not one column centered? This is appearing on every theme so far for this one transcript. But I guess this might just be a viewer problem.

<img width="1313" alt="Screenshot 2024-10-23 at 13 20 58" src="https://github.com/user-attachments/assets/123db82e-d8a3-49bd-85ab-e603dc61b6db">

**Comment by allanaaa** [comment] 2024-10-23 17:28
Cozy is showing fine on the item page but weird on the media page (that's the Sharing module button to the right of it) - looks like a flex issue maybe:

<img width="1297" alt="Screenshot 2024-10-23 at 13 26 01" src="https://github.com/user-attachments/assets/dd22ba52-daac-4ddb-83a6-ee4d1482db4c">
<img width="1344" alt="Screenshot 2024-10-23 at 13 26 11" src="https://github.com/user-attachments/assets/5539c7d5-95da-4483-9dec-36a07091a533">

**Comment by allanaaa** [comment] 2024-10-23 17:33
On Lively the media page is displaying the "Media render" and "Media render (with value annotations)" blocks differently - the latter correctly full-width, the former a narrow version that should be fixed.

http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-fifth-site/media/24016#lg=1&slide=0

**Comment by allanaaa** [comment] 2024-10-23 17:37
On all of our full-width themes the viewer has some empty space on the outsides of the two columns, which does look a bit funny with the vertical scrolls on both. Again, probably a viewer problem and not our problem - but I suppose we could enforce a maximum width?

<img width="1647" alt="Screenshot 2024-10-23 at 13 35 35" src="https://github.com/user-attachments/assets/5b76cb96-5059-4277-93ac-3fae938d67f1">

**Comment by zerocrates** [comment] 2024-10-23 21:22
On the empty space, the last of these: the viewer intentionally doesn't expand the text beyond a certain width out of concern for readability.

On the earlier one, one column centered is the correct intended rendering when there aren't two things (so, if there's no transcript, or no index, the one that is there should be rendered centered like that).

We write this viewer we're using here, but I don't know that there's something we want to change in either case here.

**Comment by zerocrates** [comment] 2024-10-23 21:38
On the untitled items that's not a CSV specific issue, the same thing happens when you add an item normally and map something to Title, the stored "real" title doesn't get updated (unless/until you go edit and save the item again afterwards, then it will update).

It's an Extract Metadata issue, not OHMS or CSV Import specific.

**Comment by zerocrates** [comment] 2024-10-23 22:21
I noticed an issue with those Papers screenshots: the iframe background is transparent and the Papers background shows through. It's fine there but could cause issues on actually dark backgrounds, so I've changed the viewer to force a white background. Pulling the module will pick up that change.

**Comment by allanaaa** [comment] 2024-10-24 16:11
> On the untitled items that's not a CSV specific issue, the same thing happens when you add an item normally and map something to Title, the stored "real" title doesn't get updated (unless/until you go edit and save the item again afterwards, then it will update).
> 
> It's an Extract Metadata issue, not OHMS or CSV Import specific.

Okay. What do we want to recommend in the documentation? "Edit the item, save it, and you should see the title update"? On the Extract Metadata page only?

(Any chance of fixing that in the newest EM release?)

**Comment by allanaaa** [comment] 2024-10-24 16:14
> I noticed an issue with those Papers screenshots: the iframe background is transparent and the Papers background shows through. It's fine there but could cause issues on actually dark backgrounds, so I've changed the viewer to force a white background. Pulling the module will pick up that change.

That's fixed.

**Comment by zerocrates** [comment] 2024-10-24 17:35
I think the note on that makes sense in just the Extract Metadata page... I'll have a look to see how simple a fix for it might be, but it shouldn't affect the release/schedule for this one either way I think.

**Comment by sharonmleon** [comment] 2024-10-24 18:29
If that fix goes in EM, I think we're ready to merge the documentation?

**Closed as completed** 2024-10-24 20:05 UTC
